language: android
android:
   components:
      - tools
      - tools # required twice per travis-ci/travis-ci#6040
      - platform-tools
      - build-tools-24.0.2
      - android-24
      - extra-android-m2repository
script:
   - ./gradlew clean testMadaniRelease -PdisableCrashlytics
