name: Android Pull Request and Merge
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    needs: [build]
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Run tests
        run: ./gradlew testMadaniDebug feature:audio:testDebug -PdisableCrashlytics -PdisableFirebase

      - name: Upload test report
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: unit_test_report
          path: app/build/reports/tests/testMadaniDebugUnitTest/

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the Code
        uses: actions/checkout@v2

      - name: Setup JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Build debug APK
        run: ./gradlew assembleMadaniDebug
